/*
 *   IRC - Internet Relay Chat, src/version.c
 *   Copyright (C) 1990 Chelsea Ashley Dyerman
 *   Copyright (C) 2010 Elizabeth Jennifer Myers
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 1, or (at your option)
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * This file is generated by version.c.SH. Any changes made will go away.
 */

#include "patchlevel.h"
#include "serno.h"

const char *generation = "1";
const char *creation = "Thu Jan 23 2014 at 15:48:21 PST";
const char *platform = "Linux 3.2.0-4-amd64 x86_64";
const char *ircd_version = IRCVERSION;
const char *patchlevel = PATCHLEVEL;
const char *serno = SERNO;

const char *infotext[] =
{
  "IRC --",
  "Based on the original code written by Jarkko Oikarinen",
  "Copyright (c) 1988-1991 University of Oulu, Computing Center",
  "Copyright (c) 1996-2001 Hybrid Development Team", 
  "Copyright (c) 2002-2009 ircd-ratbox Development Team",
  "Copyright (c) 2005-2010 charybdis development team",
  "Copyright (c) 2010 Shadowircd development team",
  "Copyright (c) 2010-2011 SporksIRCD development team",
  "",
  "This program is free software; you can redistribute it and/or",
  "modify it under the terms of the GNU General Public License as",
  "published by the Free Software Foundation; either version 2, or",
  "(at your option) any later version.",
  "",
  "SporksIRCD is a fork of ShadowIRCD with features that are required by the",
  "SporksMoo IRC network, with an emphasis on clean code. ",
  " ",
  "The SporksIRCD team is listed in nick-alphabetical order:",
  " ",
  "awilcox, Andrew R. Wilcox, <awilcox -at- wilcox-tech.com>, project deputy",
  "Elizacat, Elizabeth J. Myers, <elizabeth -at- sporksmoo.net>, head of project",
  "lstarnes, Lee T. Starnes, <lstarnes -at- sporksmoo.net>, project deputy",
  "miniCruzer, Samuel J. Hoffman, <minicruzer -at- live.com>, contributor",
  " ",
  "SporksIRCD continues to pull changes from all the aforementioned projects",
  "below. ",
  " ",
  "The SporksIRCD project would like to give thanks to the following projects; the",
  "developers of all the projects below are far too numerous to name, but our",
  "thanks goes to them.",
  " ",
  "ShadowIRCD:",
  "ShadowIRCd 6 is a modern restart of the old ShadowIRCd project based on",
  "Charybdis with a few additional features to make it appeal more to more users.",
  " ",
  "Some ShadowIRCd 6 features such as remote RESTART, DIE, and MOD* commands were",
  "borrowed from ircd-seven.",
  " ",
  "ShadowIRCD's credits can be found at:",
  "http://hg.atheme.org/unofficial/shadowircd/unofficial/shadowircd/file/tip/CREDITS",
  " ",
  "ircd-seven:",
  "ircd-seven is developed to meet the policy needs of the freenode IRC network.",
  "The ircd is based closely on Charybdis, which in turn is a fork of ircd-ratbox.",
  " ",
  "ircd-seven's credits can be found at:",
  "http://dev.freenode.net/ircd-seven/browser/CREDITS",
  " ",
  "Charybdis:",
  "Charybdis started as an evolution from ircd-ratbox. Its development is led by a",
  "team of dedicated developers who have put a lot of time into the project, and",
  "it has seen use on a variety of different network configurations.",
  " ",
  "Charybdis's credits can be found at:",
  "http://hg.atheme.org/charybdis/charybdis/file/tip/CREDITS",
  " ",
  "ircd-ratbox: ",
  "ircd-ratbox is an evolution where ircd-hybrid left off around version 7-rc1.",
  " ",
  "ircd-ratbox's credits can be found at:",
  "http://svn.ratbox.org/svnroot/ircd-ratbox/trunk/CREDITS",
  " ",
  "Visit the SporksIRCD channel on IRC at: irc.sporksmoo.net #sporksircd",
  "",
  0,
};
